import { List } from "react-window";
import RowComponent from "./rowComponent";

const App = () => {
  const names = [
    "Aarav Sharma",
    "Vivaan Patel",
    "Aditya Singh",
    "Vihaan Gupta",
    "Arjun Kumar",
    "Sai Reddy",
    "Reyansh Nair",
    "Krishna Das",
    "Ishaan Joshi",
    "Rohan Chopra",
    "Ananya Mehta",
    "Diya Iyer",
    "Aadhya Verma",
    "Kiara Ghosh",
    "Myra Nanda",
    "Sara Kaur",
    "Ira Bose",
    "Meera Rao",
    "Mishka Malhotra",
    "Anaya Kapoor",
    "Kabir Sharma",
    "Arnav Patel",
    "Dev Singh",
    "Atharv Gupta",
    "Dhruv Kumar",
    "Advait Reddy",
    "Shaurya Nair",
    "Rudra Das",
    "Yash Joshi",
    "Ayaan Chopra",
    "Pari Mehta",
    "Aarohi Iyer",
    "Ishita Verma",
    "Navya Ghosh",
    "Aanya Nanda",
    "Vanya Kaur",
    "Nisha Bose",
    "Riya Rao",
    "Saanvi Malhotra",
    "Tara Kapoor",
    "Aarav Mehta",
    "Vivaan Verma",
    "Aditya Das",
    "Vihaan Joshi",
    "Arjun Malhotra",
    "Sai Kapoor",
    "Reyansh Patel",
    "Krishna Kaur",
    "Ishaan Sharma",
    "Rohan Ghosh",
    "Ananya Gupta",
    "Diya Nair",
    "Aadhya Kumar",
    "Kiara Mehta",
    "Myra Singh",
    "Sara Iyer",
    "Ira Das",
    "Meera Verma",
    "Mishka Nanda",
    "Anaya Chopra",
    "Kabir Joshi",
    "Arnav Patel",
    "Dev Sharma",
    "Atharv Gupta",
    "Dhruv Kapoor",
    "Advait Mehta",
    "Shaurya Nair",
    "Rudra Verma",
    "Yash Malhotra",
    "Ayaan Ghosh",
    "Pari Kaur",
    "Aarohi Rao",
    "Ishita Nanda",
    "Navya Patel",
    "Aanya Joshi",
    "Vanya Sharma",
    "Nisha Chopra",
    "Riya Mehta",
    "Saanvi Gupta",
    "Tara Verma",
    "Aarav Ghosh",
    "Vivaan Iyer",
    "Aditya Rao",
    "Vihaan Das",
    "Arjun Malhotra",
    "Sai Kapoor",
    "Reyansh Nanda",
    "Krishna Joshi",
    "Ishaan Verma",
    "Rohan Patel",
    "Ananya Kaur",
    "Diya Sharma",
    "Aadhya Mehta",
    "Kiara Singh",
    "Myra Gupta",
    "Sara Verma",
    "Ira Malhotra",
    "Meera Kapoor",
    "Mishka Iyer",
    "Anaya Rao",
    // ... repeat with variations until you have 1000 entries
  ];

  return (
    <>
      <h1>virtualised component</h1>
      <RowComponent names={names} />
    </>
  );
};

export default App;
